### ISSUE TITLE
model_selection_precomputed.py文件中，关于normalization的问题

### ISSUE THREAD

**Issue by lihaohaode** [jajupmochi/py-graph#1]
Hi，linlin同学。两个问题想请教下：
1.在model_selection_precomputed.py文件中,144行我看到您想删除和自身核函数为0的图
# remove graphs whose kernels with themselves are zeros
  Kmatrix 删除Kmatrix_diag中值为0的坐标处的行和列
但在151行中，normalization又取了Kmatrix_diag的值重新赋给Kmatrix，我使用自己的测试数据（因为我没能把你完整的代码跑下来）发现如果上一步中Kmatrix_diag如果有0的元素出现，这里的乘积为0，相除数组越界。请问这一个公式的目的是什么，你会遇到这个bug吗
# normalization
          Kmatrix[i][j] /= np.sqrt(Kmatrix_diag[i] * Kmatrix_diag[j])
          Kmatrix[j][i] = Kmatrix[i][j]`
2.另外在几个"run_"和"test_"开头的ipynb文件中发现几个变量名错误（大小写之类，可能是留下的版本不同的代码？或者是我比较菜没看出来），所以请问您这套代码哪些是新的可以使用的，哪些是旧的不用的，我在测试中notebook目录下的ipynb文件出现的问题比较多，求大神指教，谢谢！

**Comment by jajupmochi** [comment]
您好，感谢问题。 问题已修复。 [commits](https://github.com/jajupmochi/py-graph/commit/ddd921696a4db427daba87ad04bfd5a14ffe5e1a)

1. model selection 中 Gram matrix 的 normalization 部分有误， `Kmatrix_diag` 应在矩阵去除对角线零元素后更新。 Normalization 的目的是消减 graph 相对大小对 kernel 值的影响。 [新代码](https://github.com/jajupmochi/py-graph/blob/62ede297d6d19c428b5f957e1482e9a979886064/pygraph/utils/model_selection_precomputed.py#L143)

2. `notebooks` 目录下的文件已修正，包括所有的 .py 和 .ipynb 文件。除 `unfinished` 和 `unused` 目录下的文件，库中所有有关 graph kernels 的代码应均可正常使用。
**注意：本代码使用 `multiprocessing.Pool.imap_unordered` 函数并行运算，该函数在 windows 系统下可能无法运行。目前在 windows 下可能需手动注释并行部分代码并使用串行直接运算，该部分代码在并行代码下方并被注释。之后我们会考虑添加参数允许用户选择并行或串行方式。**

此外，我们对 `notebooks` 目录下的结构进行了调整：
- `notebooks` 目录包含六个基于线性结构的图核的测试代码;
- `tests` 目录包含先前对一些库和函数的测试代码;
- `utils` 目录包含一些有用的工具，例如检查计算所得的 Gram matrix 是否符合基本规则，获取数据集的基本参数特征等;
- `else` 目录包含我们完成相关实验时所用到的其他一些代码。

如有问题欢迎讨论。

[为了方便我的导师，将以上中文译为英文。 ] 

****

[The following is the translation of the Chinese part above, for the convenience of English speakers.]

Thanks for your questions. The problems are solved. [commits](https://github.com/jajupmochi/py-graph/commit/ddd921696a4db427daba87ad04bfd5a14ffe5e1a)

1. The normalization part of Gram matrix in model selection was a bug. `Kmatrix_diag` is supposed to be updated after the zeros on matrix's diagonal are removed. The purpose of normalization is to reduce the impact of the relavant size of graphs on the kernel values. [New code](https://github.com/jajupmochi/py-graph/blob/62ede297d6d19c428b5f957e1482e9a979886064/pygraph/utils/model_selection_precomputed.py#L143)

2. Codes in `notebooks` directory are corrected，including all .py and .ipynb file. All codes concerning graph kernels should be able to run correctly now expect the ones in the `unfinished` and `unused` directories.
**Note that this library uses `multiprocessing.Pool.imap_unordered` function to do the parallelization, which may not be able to run correctly under Windows system. For now, Windows users may need to comment the parallel codes and uncomment the codes below them which run serially. We will consider adding a parameter to control serial or parallel computations as needed.**

Besides, We re-arranged the `notebooks` directory:
- `notebooks` directory includes test codes of 6 graph kernels based on linear patterns;
- `tests` directory includes codes that test some libraries and functions;
- `utils` directory includes some useful tools, such as a Gram matrix checker and a function to get properties of datasets;
- `else` directory includes other codes that we used for experiments.

Welcome to discuss for further problems.
