### ISSUE TITLE
Weisfeiler_Lehman graph kernel

### ISSUE THREAD

**Issue by LYF14020510036** [jajupmochi/py-graph#2]
您好， 我刚刚入门graph, 请问一下 使用：Weisfeiler_Lehman graph kernel，链接矩阵必须是对称的（无向图）吗？？？

**Comment by jajupmochi** [comment]
In original paper and my implementation, only undirected graphs are considered. Check [this](http://www.jmlr.org/papers/volume12/shervashidze11a/shervashidze11a.pdf) paper. However there may be upgrades of the kernel recently. You may check [this](https://github.com/benedekrozemberczki/awesome-graph-classification) repository for more information.

**Comment by LYF14020510036** [comment]
Thank you
